/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProprietesRouteImport } from './routes/_authenticated/proprietes'
import { Route as AuthenticatedLocatairesRouteImport } from './routes/_authenticated/locataires'
import { Route as AuthenticatedContratsRouteImport } from './routes/_authenticated/contrats'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProprietesRoute = AuthenticatedProprietesRouteImport.update({
  id: '/proprietes',
  path: '/proprietes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocatairesRoute = AuthenticatedLocatairesRouteImport.update({
  id: '/locataires',
  path: '/locataires',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratsRoute = AuthenticatedContratsRouteImport.update({
  id: '/contrats',
  path: '/contrats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/contrats': typeof AuthenticatedContratsRoute
  '/locataires': typeof AuthenticatedLocatairesRoute
  '/proprietes': typeof AuthenticatedProprietesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contrats': typeof AuthenticatedContratsRoute
  '/locataires': typeof AuthenticatedLocatairesRoute
  '/proprietes': typeof AuthenticatedProprietesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contrats': typeof AuthenticatedContratsRoute
  '/_authenticated/locataires': typeof AuthenticatedLocatairesRoute
  '/_authenticated/proprietes': typeof AuthenticatedProprietesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/contrats' | '/locataires' | '/proprietes'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/contrats' | '/locataires' | '/proprietes' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contrats'
    | '/_authenticated/locataires'
    | '/_authenticated/proprietes'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proprietes': {
      id: '/_authenticated/proprietes'
      path: '/proprietes'
      fullPath: '/proprietes'
      preLoaderRoute: typeof AuthenticatedProprietesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locataires': {
      id: '/_authenticated/locataires'
      path: '/locataires'
      fullPath: '/locataires'
      preLoaderRoute: typeof AuthenticatedLocatairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contrats': {
      id: '/_authenticated/contrats'
      path: '/contrats'
      fullPath: '/contrats'
      preLoaderRoute: typeof AuthenticatedContratsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContratsRoute: typeof AuthenticatedContratsRoute
  AuthenticatedLocatairesRoute: typeof AuthenticatedLocatairesRoute
  AuthenticatedProprietesRoute: typeof AuthenticatedProprietesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContratsRoute: AuthenticatedContratsRoute,
  AuthenticatedLocatairesRoute: AuthenticatedLocatairesRoute,
  AuthenticatedProprietesRoute: AuthenticatedProprietesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
